import React from "react";
import { Row, Col, Container } from "react-bootstrap";
import PageWrapper from "../components/PageWrapper";

import imgBanner from "../assets/image/racing/blue blockchain big data financial_4036080.png";
import imgC1 from "../assets/image/racing/kisspng-public-participation-organization-citizen-computer-corporate-boards-5b080af24dbf41.3067647115272537463185.png";
import imgC2 from "../assets/image/inner/about-content-2.png";
import imgC3 from "../assets/image/inner/about-content-3.png";
import imgC4 from "../assets/image/inner/about-content-4.png";
import imgT1 from "../assets/image/inner/team-image-1.png";
import imgT2 from "../assets/image/inner/team-image-2.png";
import imgT3 from "../assets/image/inner/team-image-3.png";
import imgT4 from "../assets/image/inner/team-image-4.png";
import imgT5 from "../assets/image/inner/team-image-5.png";
import imgT6 from "../assets/image/inner/team-image-6.png";
import imgT7 from "../assets/image/inner/team-image-7.png";

const AboutPage = () => {
  return (
    <>
      <PageWrapper
        headerConfig={{
          align: "right",
          button: "cta", // cta, account, null
        }}
      >
        <div className="content-section py-10 py-lg-10 bg-default-4">
          <Container>
            <Row className="align-items-center justify-content-center">
              <Col
                lg="6"
                className="order-lg-2"
                data-aos="flip-right"
                data-aos-duration="2000"
              >
                <div className="content-img text-right">
                  <img src={imgBanner} alt="" className="w-100" />
                </div>
              </Col>
              <Col xs="10" lg="6" xl="5" className="pe-xl-13 order-lg-1">
                <div className="section-title content-text mb-13">
                  <h2 className="title gr-text-3 mb-6 heading-color">
                    Tokenomics
                  </h2>
                  <p className="gr-text-8 text-color-opacity">
                    #B4mad racing is a distributed autonomous organization (DAO) backed by a cryptocurrency, the VROOOM 
                    token. This organizational and funding structure allows holders to vote on decisions and the future
                    of the organization. It allows holders to earn revenue generated by the project. It allows for easier
                    development funding. And, lastly, it creates an economic ecosystem in and around the platform.
                  </p>
                </div>
              </Col>
            </Row>
          </Container>
        </div>
        <div className="content-section pb-10 pb-lg-10 bg-default-4">
          <Container>
            <Row className="justify-content-center">
              <Col lg="10" xl="8">
                <div className="px-lg-8 px-xl-3">
                  <div className="single-block mb-11">
                    <h3 className="gr-text-8 fw-bold pb-3 heading-color">Decision Making</h3>
                    <p className="gr-text-9 text-color-opacity">
                      In a DAO, each token holder is a voting member. The project is fully owned and steered by token
                      holders. Voting on community decisions are weighted by the number of tokens held. Features,
                      marketing initiatives, and the general direction of the project are all community-lead decisions.
                    </p>
                  </div>
                  <div className="single-block mb-13">
                    <h3 className="gr-text-8 fw-bold heading-color">Project Funding</h3>
                    <p className="gr-text-9 text-color-opacity">
                      All development, marketing, infrastructure, and other expenses are paid for via the cryptocurrency
                      and its exchange for regular currencies. Funding is done via selling tokens and the token pricing,
                      much like stock in a company, will increase as the project progresses. Early investors will
                      receive larger quantities of tokens for their investment, much like seed or angel investors in
                      traditional companies.
                    </p>
                    </div>
                  <div className="single-block mb-11">
                    <h3 className="gr-text-8 fw-bold pb-3 heading-color">Revenue Participation</h3>
                    <p className="gr-text-9 text-color-opacity">
                      The DAO may choose to reward token holders with payments out of the profit from revenue streams
                      generated by the project. Much like traditional corporate dividends, token holders would receive
                      payments commensurate with the quantities of tokens held. 
                    </p>
                  </div>
              </div>
              </Col>
            </Row>
          </Container>
        </div>

      </PageWrapper>
    </>
  );
};
export default AboutPage;
