import React from "react";
import { Row, Col, Container } from "react-bootstrap";
import PageWrapper from "../components/PageWrapper";

import imgBanner from "../assets/image/racing/blue blockchain big data financial_4036080.png";
import imgC1 from "../assets/image/racing/kisspng-public-participation-organization-citizen-computer-corporate-boards-5b080af24dbf41.3067647115272537463185.png";
import imgC2 from "../assets/image/inner/about-content-2.png";
import imgC3 from "../assets/image/inner/about-content-3.png";
import imgC4 from "../assets/image/inner/about-content-4.png";
import imgT1 from "../assets/image/inner/team-image-1.png";
import imgT2 from "../assets/image/inner/team-image-2.png";
import imgT3 from "../assets/image/inner/team-image-3.png";
import imgT4 from "../assets/image/inner/team-image-4.png";
import imgT5 from "../assets/image/inner/team-image-5.png";
import imgT6 from "../assets/image/inner/team-image-6.png";
import imgT7 from "../assets/image/inner/team-image-7.png";

const AboutPage = () => {
  return (
    <>
      <PageWrapper
        headerConfig={{
          align: "right",
          button: "cta", // cta, account, null
        }}
      >
        <div className="inner-banner">
          <Container>
            <Row className="justify-content-center mt-md-6 pt-24 pt-lg-29">
              <Col lg="9" xl="8">
                <div className="px-md-12 text-center mb-11 mb-lg-14">
                  <h2 className="title gr-text-2 mb-9 mb-lg-12 heading-color">Tokenomics</h2>
                  <p className="gr-text-8 text-color-opacity mb-0 text-color-opacity">
                      A decentralized autonomous organization - DAO
                  </p>
                </div>
              </Col>
              <Col xs="12">
                <div className="banner-fluid-image pt-lg-9">
                  <img src={imgBanner} alt="" className="w-100" />
                </div>
              </Col>
            </Row>
          </Container>
        </div>
        <div className="about-content pt-lg-28 pt-13 pb-13 pb-lg-25">
          <Container>
            <Row>
              <Col lg="6" className="mb-7 mb-lg-0">
                <div className="pe-xl-13">
                  <h2 className="gr-text-3 heading-color mb-0">
                  Crypto Token
                  </h2>
                </div>
              </Col>
              <Col lg="6">
                <div className="pe-xl-15">
                  <p className="gr-text-8 text-color-opacity mb-7 mb-lg-10">
                  We have created a crypto currency to enable <br/>
                    * members to vote on decisions, such as feature requests <br/>
* members to participate in revenue[a] generated by the project<br/>
* early funding of project development<br/>
* creation of an economical ecosystem on the platform
                  </p>
                </div>
              </Col>
            </Row>
          </Container>
        </div>
        <div className="content-section pt-14 pt-lg-27 pb-13 pb-lg-27 bg-default-2">
          <Container>
            <Row className="align-items-center justify-content-center">
              <Col sm="8" lg="5" xl="6" className="mb-9 mb-lg-0">
                <div className="content-grid-image-group d-flex  mx-sm-n3">
                  <div className="single-image d-flex flex-column px-3 px-sm-6">
                    <img
                      src={imgC1}
                      alt=""
                      data-aos="zoom-in"
                      data-aos-duration="500"
                      className="w-100 pb-6 pb-sm-9 rounded-10"
                    />
{/* 
                    <img
                      src={imgC2}
                      alt=""
                      data-aos="zoom-in"
                      data-aos-duration="500"
                      data-aos-delay="800"
                      className="w-100 pb-6 pb-sm-9 rounded-10"
                    />
                  </div>
                  <div className="single-image d-flex flex-column pt-11 px-3 px-sm-6">
                    <img
                      src={imgC3}
                      alt=""
                      data-aos="zoom-in"
                      data-aos-duration="500"
                      data-aos-delay="400"
                      className="w-100 pb-6 pb-sm-9 rounded-10"
                    />

                    <img
                      src={imgC4}
                      alt=""
                      data-aos="zoom-in"
                      data-aos-duration="500"
                      data-aos-delay="1200"
                      className="w-100 rounded-10"
                    /> */}
                  </div>
                </div>
              </Col>
              <Col
                sm="8"
                lg="6"
                xl="5"
                className="offset-lg-1 offset-lg-1 offset-xl-0"
              >
                <div className="content-text">
                  <h2 className="gr-text-3 heading-color mb-7 mb-lg-11">
                  Community participation

                  </h2>
                  <p className="gr-text-8 text-color-opacity mb-7 mb-lg-10">
                  The project is structured as a DAO - a Decentralized autonomous organization. The project is fully owned and steered by the DAO, i.e. each token holder is a voting member of the DAO.

To enable a fair community vote on project decisions such as features, marketing, and direction, the token serves as a weighted vote.

We plan to allow members to take over decision-making immediately.


                  </p>                
                </div>
              </Col>
            </Row>
          </Container>
        </div>

        <div className="main-block pb-21">
          <Container>
            <Row className="justify-content-center">
              <Col lg="10" xl="8">
                <div className="px-lg-8 px-xl-3">
                  <div className="single-block mb-11">
                    <h3 className="gr-text-8 fw-bold pb-3 heading-color">Revenue participation
</h3>
                    <p className="gr-text-9 text-color-opacity">
                    Like a traditional company share might pay out a dividend and therefore incentivize owners to hold the share, owners of the Vrooom token will participate in all revenue generated by the platform. This creates a strong identification and bond between them and the platform.


                    </p>
                  </div>
                  <div className="single-block mb-13">
                    <h3 className="gr-text-8 fw-bold heading-color">Project funding
</h3>
<p className="gr-text-9 text-color-opacity">
In order to bootstrap the project, we depend on early seed investors. This funding is done by selling tokens, pricing will depend on the progress of the project. Pretty much like a traditional seed investor would get company shares at an early discounted price.
<br/>
The acquired money is used to cover costs, such as developers, contractors and infrastructure.
<br/>
Additionally, the tokens can be used as an alternative currency to pay and incentivize developers and contributors.



                    </p>
                    </div>
                    <div className="single-block mb-13">
                    <h3 className="gr-text-8 fw-bold heading-color">Economical Ecosystem</h3>
                    <ul className="list-unstyled">
                      <li className="mt-7 text-color-opacity">
                        <i
                          className="rounded-circle bg-dark d-inline-block me-5"
                          css={`
                            width: 9px;
                            height: 9px;
                          `}
                        ></i>
                        tokens are used to pay the service subscription

                      </li>
                      <li className="mt-7 text-color-opacity">
                        <i
                          className="rounded-circle bg-dark d-inline-block me-5"
                          css={`
                            width: 9px;
                            height: 9px;
                          `}
                        ></i>
                     tokens are used to get access to products created on the platform

                      </li>
                      <li className="mt-7 text-color-opacity">
                        <i
                          className="rounded-circle bg-dark d-inline-block me-5"
                          css={`
                            width: 9px;
                            height: 9px;
                          `}
                        ></i>
payment for any additional digital good or services transaction

                      </li>
                      <li className="mt-7 text-color-opacity">
                        <i
                          className="rounded-circle bg-dark d-inline-block me-5"
                          css={`
                            width: 9px;
                            height: 9px;
                          `}
                        ></i>
Vrooom might be converted from and to other currencies (crypto or real) on distributed exchanges.

                      </li>
                      <li className="mt-7 text-color-opacity">
                        <i
                          className="rounded-circle bg-dark d-inline-block me-5"
                          css={`
                            width: 9px;
                            height: 9px;
                          `}
                        ></i>
a virtual wallet for crypto currencies is required to own Vrooom

                      </li>
                    </ul>
                  </div>

                  {/* <div className="single-block mb-11">
                    <h3 className="gr-text-8 fw-bold pb-3 heading-color">Market Analysis

</h3>
                    <p className="gr-text-9 text-color-opacity">
                    iRacing has 200k users, which subscribe to their paid subscription. Racedepartment.com used SteamDB to see how many players are playing some of the more popular games. The combined 24-hour peaks of the games are ~30k concurrent average players for the more simulation-focused games. Racedepartment.com itself has 2 million registered members. They also offer a similar product to #B4mad Racing -  called https://www.simracing.gp/ - which is currently in beta but does not seem to be focused so much on telemetry data and driver history.
</p>
<p className="gr-text-9 text-color-opacity">

Let’s assume we have a market of 1.000.000 potential users and every 4th user signs up for the free service. This will result in 250.000 registered users. If we have a conservative conversion rate of 10% into the paid tier, we’d get 25.000 paying subscribers.
The average cost of a paid product is approx 5 USD / month, resulting in 125.000 USD monthly revenue.


                    </p>
                  </div> */}
              </div>
              </Col>
            </Row>
          </Container>
        </div>

      </PageWrapper>
    </>
  );
};
export default AboutPage;
